apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pisbv06ef-nodejs 
  janus-idp.io/tekton: pisbv06ef-nodejs
  backstage.io/kubernetes-id: pisbv06ef-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pisbv06ef-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml