apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pisbv06ef-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pisbv06ef-nodejs 
  name: pisbv06ef-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pisbv06ef-nodejs 
